---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
type: Opaque
data:
  name: {{ (toString (.Values.config.salt_config.user)) | b64enc | quote }}
  pswd: {{ (toString (.Values.config.salt_config.password)) | b64enc | quote }}
  eauth: {{ (toString (.Values.config.salt_config.eauth)) | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-creds-statetreegit
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
type: Opaque
data:
  url: {{ (toString (.Values.stateTreeGit.url)) | b64enc | quote }}
  key: {{ (toString (.Values.stateTreeGit.base64Key)) | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-creds-vernemq
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
type: Opaque
data:
  ssl: {{ (toString (.Values.vernemq.ssl)) | b64enc | quote }}
  url: {{ (toString (.Values.vernemq.url)) | b64enc | quote }}
  port: {{ (toString (.Values.vernemq.port)) | b64enc | quote }}
  user: {{ (toString (.Values.vernemq.user)) | b64enc | quote }}
  pswd: {{ (toString (.Values.vernemq.pswd)) | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-meta-creds-vernemq
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
type: Opaque
data:
  useSsl: {{ (toString (.Values.ingress.localVmq.useSsl)) | b64enc | quote }}
  port: {{ (toString (.Values.ingress.localVmq.port)) | b64enc | quote }}
  user: {{ (toString (.Values.ingress.localVmq.user)) | b64enc | quote }}
  pswd: {{ (toString (.Values.ingress.localVmq.pswd)) | b64enc | quote }}
  wssPort: {{ (toString (.Values.ingress.localVmq.wssPort)) | b64enc | quote }}
---
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-creds-saltuser
  labels: {{ .Release.Namespace }}
type: Opaque
data:
  name: {{ (toString (.Values.config.salt_config.user)) | b64enc | quote }}
  pswd: {{ (toString (.Values.config.salt_config.password)) | b64enc | quote }}
  eauth: {{ (toString (.Values.config.salt_config.eauth)) | b64enc | quote }}
...
